use_frameworks!

platform :ios, '10.0'

target 'FHXFloatingButton_Example' do
  pod 'FHXFloatingButton', :path => '../'

  target 'FHXFloatingButton_Tests' do
    inherit! :search_paths

    
  end
end
